// This file is automatically generated. Do not edit it directly.
// Supabase client will be properly configured once the package is installed correctly

// Temporary placeholder - will be replaced with proper Supabase client
export const supabase = {
  auth: {
    signUp: () => Promise.resolve({ data: null, error: null }),
    signIn: () => Promise.resolve({ data: null, error: null }),
    signOut: () => Promise.resolve({ error: null }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  }
};

// Database schema will be properly configured
export type Database = {};