// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqiapfuamkfefrofzfve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaWFwZnVhbWtmZWZyb2Z6ZnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODQ5NTUsImV4cCI6MjA3Mzg2MDk1NX0.8qAb7FqsFbL3GwOQu9BetI3ZxhHBkeBqyfdB8soW4lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});